[providers]
node = true

[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'corepack enable',
  'pnpm install --frozen-lockfile'
]

[phases.build] 
cmds = ['pnpm build']

[start]
cmd = 'cd packages/api && node dist/index.js'
