providers = ["python"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PORT = "8000"
PYTHONPATH = "/app/ai-adwords"

[phases.build]
cmds = [
  "cd ai-adwords",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "cd ai-adwords && python start_app.py"
