[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PORT = "8000"
PYTHONPATH = "/app/ai-adwords"

[phases.build]
cmds = [
  "cd ai-adwords",
  "pip install poetry",
  "poetry config virtualenvs.create false",
  "poetry install --only=main --no-interaction"
]

[phases.start]
cmd = "cd ai-adwords && python start_app.py"
