[build]
builder = "nixpacks"

[deploy]
startCommand = "./start-production.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "web-frontend"
source = "apps/web"
domains = ["${{RAILWAY_PUBLIC_DOMAIN}}"]

[services.web-frontend.variables]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "api-server" 
source = "packages/api"

[services.api-server.variables]
NODE_ENV = "production"
PORT = "8088"

[[services]]
name = "ai-services"
source = "ai-adwords"

[services.ai-services.variables]
PORT = "8000"
PYTHON_VERSION = "3.11"

[[services]]
name = "workers"
source = "packages/workers"

[services.workers.variables]
NODE_ENV = "production"
