version: '3.8'

services:
  ppc-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://synter_user:synter_pass@postgres:5432/synter_ppc
      - GOOGLE_ADS_DEVELOPER_TOKEN=${GOOGLE_ADS_DEVELOPER_TOKEN}
      - GOOGLE_ADS_CLIENT_ID=${GOOGLE_ADS_CLIENT_ID}
      - GOOGLE_ADS_CLIENT_SECRET=${GOOGLE_ADS_CLIENT_SECRET}
      - GOOGLE_ADS_REFRESH_TOKEN=${GOOGLE_ADS_REFRESH_TOKEN}
      - GOOGLE_ADS_LOGIN_CUSTOMER_ID=${GOOGLE_ADS_LOGIN_CUSTOMER_ID}
      - GOOGLE_ADS_CUSTOMER_ID=${GOOGLE_ADS_CUSTOMER_ID}
      - APP_BASIC_AUTH_USER=${APP_BASIC_AUTH_USER:-admin}
      - APP_BASIC_AUTH_PASS=${APP_BASIC_AUTH_PASS:-change-me}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=synter_user
      - POSTGRES_PASSWORD=synter_pass
      - POSTGRES_DB=synter_ppc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synter_user -d synter_ppc"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
